[----------] Running tests from PanickingTest
[ RUN      ] PanickingTest.PanickingTest
TearDown running.
panicking_test.go:44:
panic: foobar

runtime.Caller
	some_file.txt:0
github.com/jacobsa/ogletest.formatPanicStack
	some_file.txt:0
github.com/jacobsa/ogletest._func_006
	some_file.txt:0
runtime.panic
	some_file.txt:0
github.com/jacobsa/ogletest/somepkg_test.(*PanickingTest).PanickingTest
	some_file.txt:0
reflect.Value.call
	some_file.txt:0
reflect.Value.Call
	some_file.txt:0
github.com/jacobsa/ogletest.runMethodIfExists
	some_file.txt:0
github.com/jacobsa/ogletest._func_003
	some_file.txt:0
github.com/jacobsa/ogletest.runWithProtection
	some_file.txt:0
github.com/jacobsa/ogletest.runTest
	some_file.txt:0
github.com/jacobsa/ogletest.runTestsInternal
	some_file.txt:0
github.com/jacobsa/ogletest._func_005
	some_file.txt:0
sync.(*Once).Do
	some_file.txt:0
github.com/jacobsa/ogletest.RunTests
	some_file.txt:0
github.com/jacobsa/ogletest/somepkg_test.TestPanickingTest
	some_file.txt:0
testing.tRunner
	some_file.txt:0
runtime.goexit
	some_file.txt:0


[  FAILED  ] PanickingTest.PanickingTest
[ RUN      ] PanickingTest.ZzzSomeOtherTest
TearDown running.
[       OK ] PanickingTest.ZzzSomeOtherTest
[----------] Finished with tests from PanickingTest
--- FAIL: somepkg (1.23 seconds)
FAIL
exit status 1
FAIL somepkg 1.234s
